# Generated by Django 4.1.7 on 2023-04-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First_Name', max_length=255)),
                ('last_name', models.CharField(blank=True, db_column='Last_Name', max_length=255, null=True)),
                ('phone', models.CharField(db_column='Phone', max_length=20, unique=True)),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('pswd', models.CharField(db_column='Pswd', max_length=255)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(db_column='Driver_id', primary_key=True, serialize=False)),
                ('dl_id', models.CharField(db_column='DL_ID', max_length=10, unique=True)),
                ('first_name', models.CharField(db_column='First_Name', max_length=255)),
                ('last_name', models.CharField(blank=True, db_column='Last_Name', max_length=255, null=True)),
                ('phone', models.CharField(db_column='Phone', max_length=20, unique=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True, unique=True)),
                ('pswd', models.CharField(db_column='Pswd', max_length=255)),
            ],
            options={
                'db_table': 'Driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(db_column='Payment_id', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('paytime', models.CharField(db_column='Paytime', max_length=10)),
                ('method', models.CharField(db_column='Method', max_length=40)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_plate', models.CharField(db_column='VEHICLE_PLATE', max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(db_column='COMPANY', max_length=256)),
                ('manu_year', models.IntegerField(db_column='Manu_year')),
                ('model', models.CharField(db_column='MODEL', max_length=256)),
            ],
            options={
                'db_table': 'VEHICLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('customer', models.ForeignKey(db_column='Customer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='firstapp.customer')),
                ('ride_date', models.CharField(db_column='RIDE_DATE', max_length=20)),
                ('ride_time', models.CharField(db_column='RIDE_TIME', max_length=20)),
                ('pickup_loc', models.CharField(db_column='Pickup_loc', max_length=255)),
                ('drop_loc', models.CharField(db_column='DROP_LOC', max_length=255)),
                ('ride_otp', models.IntegerField(db_column='RIDE_OTP')),
                ('completion_status', models.CharField(db_column='Completion_status', max_length=10)),
            ],
            options={
                'db_table': 'Ride',
                'managed': False,
            },
        ),
    ]
